# Database Connections
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/LearnSpring}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:system123#}

# Security
jwt.secret=${JWT_SECRET:your_super_secret_local_key_for_dev_only}

# Microservices
python.ai.url=${PYTHON_URL:http://localhost:8000}

# CORS (Who is allowed to talk to this server?)
frontend.url=${FRONTEND_URL:http://localhost:5173}

# 2. The JPA Magic (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update

# 3. Optional: See the raw SQL Spring writes in your console
spring.jpa.show-sql=true